[tool.poetry]
name = "loading"
version = "0.1.0"
description = "Firts py makefile"
authors = ["acano-kr"]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.1.0"
numpy = "^1.25.0"
matplotlib = "^3.7.2"
requests = "^2.31.0"

[build-system]
build-backend = "poetry.core.mansory.api"
requires = ["poerty-core"]